---
- name: Add apt-key
  become: true
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Install repository
  become: true
  vars:
    repo_url: "deb http://dl.google.com/linux/chrome/deb/ stable main"
  apt_repository:
    repo: "{{ repo_url }}"
    state: present
    update_cache: yes
  when: repo_url not in apt_sources

- name: Install chrome
  become: true
  apt:
    name: google-chrome-stable
    state: present
